version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    volumes:
      - .:/app
      - /home/fatemeh/Documents/training_datasets/output2:/dataset1


volumes:
  mongo-data:
